In [ ]:
syllabus = {
  "sem": 5,
  "subs": [
    [
      "main",
      "AD2511"
    ],
    [
      "main",
      "AD2512"
    ],
    [
      "main",
      "AD2513"
    ],
    [
      "main",
      "AD2514"
    ],
    [
      "main",
      "AD2515"
    ],
    [
      "elective",
      "AD2V11"
    ],
    [
      "VAC",
      "AD2VA1"
    ],
    [
      "labs",
      "AD2581"
    ]
  ]
}

In [ ]:
subjects = [['AD2511', 'DC', 'Distributed Computing', 3, 'ADS'], ['AD2512', 'DL', 'Deep Learning', 3, 'ADS'], ['AD2513', 'BDT', 'Big Data Technologies', 3, 'ADS'], ['AD2514', 'CC', 'Cloud Computing', 3, 'ADS'], ['AD2515', 'XWS', 'XML and Web Services', 3, 'ADS'], ['AD2V11', 'MAD', 'Mobile Application Development', 3, 'ADS'], ['AD2VA1', 'DT', 'Design Thinking', 3, 'ADS'], ['AD2581', 'DL LAB', 'Deep Learning Laboratory', 1.5, 'ADS']]

In [ ]:
import random
from prettytable import PrettyTable

# Define syllabus
syllabus = {
    "sem": 5,
    "subs": [
        ["main", "AD2511"],
        ["main", "AD2512"],
        ["main", "AD2513"],
        ["main", "AD2514"],
        ["main", "AD2515"],
        ["elective", "AD2V11"],
        ["VAC", "AD2VA1"],
        ["labs", "AD2581"]
    ]
}

# Extract subjects based on types
subjects_dict = {
    "main": [sub[1] for sub in syllabus["subs"] if sub[0] == "main"],
    "elective": [sub[1] for sub in syllabus["subs"] if sub[0] == "elective"],
    "VAC": [sub[1] for sub in syllabus["subs"] if sub[0] == "VAC"],
    "labs": [sub[1] for sub in syllabus["subs"] if sub[0] == "labs"]
}

# Constraints
days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
periods = ["9:00 - 10:00 AM", "10:00 - 11:00 AM", "11:15 AM - 12:15 PM",
           "12:15 - 1:15 PM", "2:00 - 3:00 PM", "3:00 - 4:00 PM", "4:00 - 5:00 PM"]

# Initialize empty timetable
timetable = {day: [""] * len(periods) for day in days}

# Function to randomly assign periods
def assign_periods():
    lab_assigned = False

    for day in days:
        # Create a list of subjects to assign
        available_subjects = subjects_dict["main"] + subjects_dict["elective"] + subjects_dict["VAC"]
        random.shuffle(available_subjects)

        # Ensure unique first period
        first_period = available_subjects.pop(0)
        timetable[day][0] = first_period

        # Assign other periods
        i = 1
        while i < len(periods):
            if not lab_assigned and (i == 1 or i == 4) and random.choice([True, False]):
                # Assign labs only to specific time slots (3 consecutive periods)
                timetable[day][i:i+3] = ["AD2581"] * 3
                lab_assigned = True
                i += 3
            elif available_subjects:
                subject = available_subjects.pop(0)
                timetable[day][i] = subject
                i += 1
            else:
                i += 1

# Ensure all constraints
def generate_timetable():
    while True:
        # Reset the timetable
        for day in days:
            timetable[day] = [""] * len(periods)

        assign_periods()

        # Check for unique first periods
        first_periods = [timetable[day][0] for day in days]
        if len(first_periods) == len(set(first_periods)):
            break

    return timetable

# Generate timetable
final_timetable = generate_timetable()

# Print the timetable in table format
table = PrettyTable()
table.field_names = ["Day"] + periods

for day, schedule in final_timetable.items():
    table.add_row([day] + schedule)

print(table)


+-----------+-----------------+------------------+---------------------+-----------------+----------------+----------------+----------------+
|    Day    | 9:00 - 10:00 AM | 10:00 - 11:00 AM | 11:15 AM - 12:15 PM | 12:15 - 1:15 PM | 2:00 - 3:00 PM | 3:00 - 4:00 PM | 4:00 - 5:00 PM |
+-----------+-----------------+------------------+---------------------+-----------------+----------------+----------------+----------------+
|   Monday  |      AD2514     |      AD2VA1      |        AD2515       |      AD2512     |     AD2581     |     AD2581     |     AD2581     |
|  Tuesday  |      AD2511     |      AD2V11      |        AD2512       |      AD2513     |     AD2VA1     |     AD2514     |     AD2515     |
| Wednesday |      AD2513     |      AD2514      |        AD2V11       |      AD2515     |     AD2512     |     AD2VA1     |     AD2511     |
|  Thursday |      AD2VA1     |      AD2512      |        AD2514       |      AD2V11     |     AD2515     |     AD2511     |     AD2513     |
|   Fr

In [ ]:
# Define the subjects data
subjects = [
    ['AD2511', 'DC', 'Distributed Computing', 3, 'ADS'],
    ['AD2512', 'DL', 'Deep Learning', 3, 'ADS'],
    ['AD2513', 'BDT', 'Big Data Technologies', 3, 'ADS'],
    ['AD2514', 'CC', 'Cloud Computing', 3, 'ADS'],
    ['AD2515', 'XWS', 'XML and Web Services', 3, 'ADS'],
    ['AD2V11', 'MAD', 'Mobile Application Development', 3, 'ADS'],
    ['AD2VA1', 'DT', 'Design Thinking', 3, 'ADS'],
    ['AD2581', 'DL LAB', 'Deep Learning Laboratory', 1.5, 'ADS']
]

# Define subject categories
subject_categories = [
    ["main", "AD2511"],
    ["main", "AD2512"],
    ["main", "AD2513"],
    ["main", "AD2514"],
    ["main", "AD2515"],
    ["elective", "AD2V11"],
    ["VAC", "AD2VA1"],
    ["labs", "AD2581"]
]

# Extract relevant data into a dictionary
subjects_dict = {}
for category, code in subject_categories:
    subjects_dict.setdefault(category, [])
    for sub in subjects:
        if sub[0] == code:
            subjects_dict[category].append(sub)

# Constraints
days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
periods = ["8:45 - 9:40 AM", "9:40 - 10:35 AM", "10:55 AM - 11:45 PM",
           "11:45 - 12:35 PM", "1:45 - 2:35 PM", "2:35 - 3:25 PM", "3:25 - 4:15 PM"]

# Initialize empty timetable
timetable = {day: [""] * len(periods) for day in days}
subject_hours = {sub[0]: 0 for sub in subjects}  # Track hours per subject

# Function to randomly assign periods
def assign_periods():
    lab_assigned = False

    for day in days:
        # Create a list of subjects to assign
        available_subjects = subjects_dict["main"] + subjects_dict["elective"] + subjects_dict["VAC"]
        random.shuffle(available_subjects)

        # Ensure unique first period
        first_period = available_subjects.pop(0)
        timetable[day][0] = f"{first_period[1]} ({first_period[0]})"
        subject_hours[first_period[0]] += 1

        # Assign other periods
        i = 1
        while i < len(periods):
            if not lab_assigned and (i == 1 or i == 4) and random.choice([True, False]):
                # Assign labs only to specific time slots (3 consecutive periods)
                timetable[day][i:i+3] = [f"DL LAB (AD2581)"] * 3
                subject_hours["AD2581"] += 3
                lab_assigned = True
                i += 3
            elif available_subjects:
                subject = available_subjects.pop(0)
                timetable[day][i] = f"{subject[1]} ({subject[0]})"
                subject_hours[subject[0]] += 1
                i += 1
            else:
                i += 1

# Ensure all constraints
def generate_timetable():
    while True:
        # Reset the timetable
        for day in days:
            timetable[day] = [""] * len(periods)

        assign_periods()

        # Check for unique first periods
        first_periods = [timetable[day][0] for day in days]
        if len(first_periods) == len(set(first_periods)):
            break

    return timetable

# Generate timetable
final_timetable = generate_timetable()

# Calculate periods for each subject
periods_count = {sub[0]: {"H": 0, "S": 0} for sub in subjects}
for day in days:
    for i, period in enumerate(timetable[day]):
        if period:
            code = period.split('(')[-1].strip(')')
            if day == "Saturday":
                periods_count[code]["S"] += 1
            else:
                periods_count[code]["H"] += 1

from prettytable import PrettyTable

# Print the timetable in table format
table = PrettyTable()
table.field_names = ["Day"] + periods

for day, schedule in final_timetable.items():
    table.add_row([day] + schedule)

print(table)

# Print the subject information table
print("\nSubject Information:\n")
print(f"{'Code':<8} {'Acronym':<8} {'Subject Name':<30} {'Credits':<7} {'Department':<8} {'Hours':<5} {'H':<3} {'S':<3}")
print("-" * 70)
for sub in subjects:
    code = sub[0]
    hours = subject_hours[code]
    h_periods = periods_count[code]["H"]
    s_periods = periods_count[code]["S"]
    print(f"{code:<8} {sub[1]:<8} {sub[2]:<30} {sub[3]:<7} {sub[4]:<8} {hours:<5} {h_periods:<3} {s_periods:<3}")


+-----------+----------------+-----------------+---------------------+------------------+-----------------+-----------------+-----------------+
|    Day    | 8:45 - 9:40 AM | 9:40 - 10:35 AM | 10:55 AM - 11:45 PM | 11:45 - 12:35 PM |  1:45 - 2:35 PM |  2:35 - 3:25 PM |  3:25 - 4:15 PM |
+-----------+----------------+-----------------+---------------------+------------------+-----------------+-----------------+-----------------+
|   Monday  |  XWS (AD2515)  |   CC (AD2514)   |     MAD (AD2V11)    |   BDT (AD2513)   | DL LAB (AD2581) | DL LAB (AD2581) | DL LAB (AD2581) |
|  Tuesday  |  BDT (AD2513)  |   DC (AD2511)   |     MAD (AD2V11)    |   DT (AD2VA1)    |   CC (AD2514)   |   XWS (AD2515)  |   DL (AD2512)   |
| Wednesday |  MAD (AD2V11)  |   CC (AD2514)   |     XWS (AD2515)    |   DL (AD2512)    |   DC (AD2511)   |   DT (AD2VA1)   |   BDT (AD2513)  |
|  Thursday |  DC (AD2511)   |   DT (AD2VA1)   |     MAD (AD2V11)    |   BDT (AD2513)   |   XWS (AD2515)  |   CC (AD2514)   |   DL (AD25

In [ ]:
table = PrettyTable()
table.field_names = ["Day"] + periods

for day, schedule in final_timetable.items():
    table.add_row([day] + schedule)

print(table)

+-----------+-----------------+------------------+---------------------+-----------------+----------------+----------------+----------------+
|    Day    | 9:00 - 10:00 AM | 10:00 - 11:00 AM | 11:15 AM - 12:15 PM | 12:15 - 1:15 PM | 2:00 - 3:00 PM | 3:00 - 4:00 PM | 4:00 - 5:00 PM |
+-----------+-----------------+------------------+---------------------+-----------------+----------------+----------------+----------------+
|   Monday  |   CC (AD2514)   | DL LAB (AD2581)  |   DL LAB (AD2581)   | DL LAB (AD2581) |  DL (AD2512)   |  DC (AD2511)   |  BDT (AD2513)  |
|  Tuesday  |   BDT (AD2513)  |   DC (AD2511)    |     DT (AD2VA1)     |   MAD (AD2V11)  |  DL (AD2512)   |  CC (AD2514)   |  XWS (AD2515)  |
| Wednesday |   DT (AD2VA1)   |   DL (AD2512)    |     CC (AD2514)     |   MAD (AD2V11)  |  XWS (AD2515)  |  BDT (AD2513)  |  DC (AD2511)   |
|  Thursday |   DL (AD2512)   |   CC (AD2514)    |     XWS (AD2515)    |   BDT (AD2513)  |  DC (AD2511)   |  MAD (AD2V11)  |  DT (AD2VA1)   |
|   Fr

In [ ]:
!pip install python-constraint

  Preparing metadata (setup.py) ... done
  Created wheel for python-constraint: filename=python_constraint-1.4.0-py2.py3-none-any.whl size=24059 sha256=63da89ff11cbdeb3257bdea2f2b9da0048a13b5d5f8490dc00e1d2fb4379366c
  Stored in directory: /root/.cache/pip/wheels/2e/f2/2b/cb08b5fe129e4f69b7033061f256e5c551b0aa1160c2872aee
Successfully built python-constraint


In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Example historical timetable data
data = {
    'day': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    'time_slot': ['9:00 - 10:00 AM', '10:00 - 11:00 AM', '11:00 - 12:00 PM', '1:00 - 2:00 PM', '2:00 - 3:00 PM'],
    'subject': ['Math', 'Physics', 'Chemistry', 'Biology', 'History']
}

df = pd.DataFrame(data)

# Initialize the OneHotEncoder with proper feature names
encoder = OneHotEncoder(sparse=False)
encoded_features = encoder.fit_transform(df[['day', 'time_slot']])

# Convert subjects to categorical for the target
subjects = df['subject'].unique()
subject_encoder = OneHotEncoder(sparse=False)
encoded_subjects = subject_encoder.fit_transform(df[['subject']])


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Define model
model = Sequential([
    Input(shape=(encoded_features.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(len(subjects), activation='softmax')  # Output layer with softmax for classification
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(encoded_features, encoded_subjects, epochs=10)


Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.0000e+00 - loss: 1.6385
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.0000e+00 - loss: 1.6164
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.0000e+00 - loss: 1.5949
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.0000e+00 - loss: 1.5738
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2000 - loss: 1.5532
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4000 - loss: 1.5329
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4000 - loss: 1.5137
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.8000 - loss: 1.4947
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.8000 - loss: 1.4759
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8000 - loss: 1.4572


In [ ]:
# Generate a timetable
def generate_timetable(model, encoder, subject_encoder, days, time_slots, subjects):
    timetable = []
    # Create a DataFrame for input features
    for day in days:
        for time_slot in time_slots:
            input_data = {'day': [day], 'time_slot': [time_slot]}
            # Convert input data to DataFrame
            input_df = pd.DataFrame(input_data)
            # Transform input data for prediction
            input_encoded = encoder.transform(input_df)
            # Generate prediction for subjects
            predicted_subject = model.predict(input_encoded)
            predicted_subject_index = np.argmax(predicted_subject, axis=1)
            predicted_subject_name = subjects[predicted_subject_index[0]]
            timetable.append({'day': day, 'time_slot': time_slot, 'subject': predicted_subject_name})
    return timetable

# Example usage
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
time_slots = ['9:00 - 10:00 AM', '10:00 - 11:00 AM', '11:00 - 12:00 PM', '1:00 - 2:00 PM', '2:00 - 3:00 PM']

new_timetable = generate_timetable(model, encoder, subject_encoder, days, time_slots, subjects)
print(new_timetable)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[{'day': 'Monday', 'time_slot': '9:00 - 10:00 AM',

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from pymongo import MongoClient



# Connect to MongoDB
client = MongoClient("mongodb+srv://Liyas:1122@cluster0.f8bxeps.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
db = client['ADS']
collection = db['Syllabus']

# Fetch the document
document = collection.find_one()

# Extract data
sem = document['sem']
theory = document['theory']
practicals = document['practicals']

def create_dataframe(sem, theory, practicals):
    data = []
    for period, subject in enumerate(theory + practicals):
        if len(subject) > 1:
            category, code = subject
        else:
            category, code = 'N/A', subject[0]
        is_lab = 1 if 'lab' in code.lower() else 0
        data.append([sem, period, category, code, is_lab])
    df = pd.DataFrame(data, columns=['Semester', 'Period', 'Category', 'Subject_Code', 'Is_Lab'])
    return df

df = create_dataframe(sem, theory, practicals)
print(df)

def add_constraints(df):
    df['Is_First_Period'] = df['Period'].apply(lambda x: 1 if x == 0 else 0)
    df['Is_Consecutive'] = df.groupby(['Category', 'Subject_Code'])['Period'].diff().fillna(0).apply(lambda x: 1 if x == 1 else 0)
    df['Daily_Subject_Count'] = df.groupby(['Semester', 'Subject_Code'])['Subject_Code'].transform('count')
    df['Weekly_Subject_Count'] = df.groupby(['Subject_Code'])['Subject_Code'].transform('count')
    return df

df = add_constraints(df)
print(df)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


   Semester  Period Category Subject_Code  Is_Lab
0         5       0     main       AD2511       0
1         5       1     main       AD2512       0
2         5       2     main       AD2513       0
3         5       3     main       AD2514       0
4         5       4     main       AD2515       0
5         5       5      N/A     elective       0
6         5       6      N/A          VAC       0
7         5       7     main       AD2581       0
8         5       8     main       AD2591       0
   Semester  Period Category Subject_Code  Is_Lab  Is_First_Period  \
0         5       0     main       AD2511       0                1   
1         5       1     main       AD2512       0                0   
2         5       2     main       AD2513       0                0   
3         5       3     main       AD2514       0                0   
4         5       4     main       AD2515       0                0   
5         5       5      N/A     elective       0                0   
6         

In [ ]:
X = df[['Is_Lab', 'Is_First_Period', 'Is_Consecutive', 'Daily_Subject_Count', 'Weekly_Subject_Count']]
y = df['Period']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print(y)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
Name: Period, dtype: int64


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
model = RandomForestClassifier(n_estimators=1000, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print('Accuracy:', accuracy_score(y_test, y_pred))

Accuracy: 0.0


In [ ]:
import pandas as pd
import numpy as np
from pymongo import MongoClient
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import accuracy_score

# Connect to MongoDB
client = MongoClient("mongodb+srv://Liyas:1122@cluster0.f8bxeps.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
db = client['ADS']
collection = db['Syllabus']

# Fetch the document
document = collection.find_one()

# Extract data
sem = document['sem']
theory = document['theory']
practicals = document['practicals']

# Create a DataFrame from the extracted data
def create_dataframe(sem, theory, practicals):
    data = []
    for period, subject in enumerate(theory + practicals):
        if len(subject) > 1:
            category, code = subject
        else:
            category, code = 'N/A', subject[0]
        is_lab = 1 if 'lab' in code.lower() else 0
        data.append([sem, period, category, code, is_lab])
    df = pd.DataFrame(data, columns=['Semester', 'Period', 'Category', 'Subject_Code', 'Is_Lab'])
    return df

df = create_dataframe(sem, theory, practicals)

# Add constraints to the DataFrame
def add_constraints(df):
    df['Is_First_Period'] = df['Period'].apply(lambda x: 1 if x == 0 else 0)
    df['Is_Consecutive'] = df.groupby(['Category', 'Subject_Code'])['Period'].diff().fillna(0).apply(lambda x: 1 if x == 1 else 0)
    df['Daily_Subject_Count'] = df.groupby(['Semester', 'Subject_Code'])['Subject_Code'].transform('count')
    df['Weekly_Subject_Count'] = df.groupby(['Subject_Code'])['Subject_Code'].transform('count')
    return df

df = add_constraints(df)

# Preprocess categorical variables
def preprocess_data(df):
    # One-hot encode the 'Category' and 'Subject_Code' columns
    enc = OneHotEncoder(sparse=False)
    encoded_cols = enc.fit_transform(df[['Category', 'Subject_Code']])
    encoded_df = pd.DataFrame(encoded_cols, columns=enc.get_feature_names_out())

    # Combine the encoded columns with other numerical columns
    df = pd.concat([df, encoded_df], axis=1)

    # Drop the original categorical columns
    df.drop(['Category', 'Subject_Code'], axis=1, inplace=True)

    return df

df = preprocess_data(df)

# Separate features and target
X = df.drop(columns=['Period'])
y = df['Period']

# Scale the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the Neural Network Architecture
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1)  # Predicting the period, which is a single output
])

# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Train the Model
model.fit(X_train, y_train, epochs=150, batch_size=32, validation_split=0.2, verbose=2)

# Evaluate the Model
y_pred = model.predict(X_test)
y_pred = np.round(y_pred).flatten()  # Round to the nearest period

accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/150
1/1 - 2s - 2s/step - loss: 24.4938 - mae: 4.1667 - val_loss: 32.5046 - val_mae: 5.3356
Epoch 2/150
1/1 - 0s - 128ms/step - loss: 23.6659 - mae: 4.0736 - val_loss: 31.5540 - val_mae: 5.2548
Epoch 3/150
1/1 - 0s - 54ms/step - loss: 22.9104 - mae: 3.9843 - val_loss: 30.6227 - val_mae: 5.1746
Epoch 4/150
1/1 - 0s - 47ms/step - loss: 22.2011 - mae: 3.8972 - val_loss: 29.7106 - val_mae: 5.0947
Epoch 5/150
1/1 - 0s - 57ms/step - loss: 21.4939 - mae: 3.8086 - val_loss: 28.8157 - val_mae: 5.0150
Epoch 6/150
1/1 - 0s - 48ms/step - loss: 20.7949 - mae: 3.7193 - val_loss: 27.9389 - val_mae: 4.9357
Epoch 7/150
1/1 - 0s - 58ms/step - loss: 20.1026 - mae: 3.6293 - val_loss: 27.0766 - val_mae: 4.8564
Epoch 8/150
1/1 - 0s - 47ms/step - loss: 19.4255 - mae: 3.5407 - val_loss: 26.2301 - val_mae: 4.7773
Epoch 9/150
1/1 - 0s - 46ms/step - loss: 18.7623 - mae: 3.4520 - val_loss: 25.4004 - val_mae: 4.6985
Epoch 10/150
1/1 - 0s - 48ms/step - loss: 18.1351 - mae: 3.3700 - val_loss: 24.5703 - val_ma

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

# Assuming the data is already preprocessed and loaded in DataFrame `df`
# Define the subjects and periods
subjects = ['DL (AD2512)', 'CC (AD2514)', 'XWS (AD2515)', 'DC (AD2511)', 'DT (AD2VA1)', 'MAD (AD2V11)', 'BDT (AD2513)']
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

# # Load the trained model
# model = tf.keras.models.load_model('model_name.h5')

# Predict the periods for each subject
X = df.drop(columns=['Period'])
y_pred = model.predict(X)
y_pred = np.round(y_pred).flatten()

# Create an empty timetable
timetable = pd.DataFrame('', index=days, columns=[
    '8:45 - 9:40 AM', '9:40 - 10:35 AM', '10:55 AM - 11:45 AM',
    '11:45 - 12:35 PM', '1:45 - 2:35 PM', '2:35 - 3:25 PM', '3:25 - 4:15 PM'
])

# Assign subjects to periods based on predictions
for i, period in enumerate(y_pred):
    day_index = i // len(timetable.columns)
    period_index = i % len(timetable.columns)
    timetable.iloc[day_index, period_index] = subjects[i % len(subjects)]

# Print the timetable
print(timetable)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
          8:45 - 9:40 AM 9:40 - 10:35 AM 10:55 AM - 11:45 AM 11:45 - 12:35 PM  \
Monday       DL (AD2512)     CC (AD2514)        XWS (AD2515)      DC (AD2511)   
Tuesday      DL (AD2512)     CC (AD2514)                                        
Wednesday                                                                       
Thursday                                                                        
Friday                                                                          
Saturday                                                                        

          1:45 - 2:35 PM 2:35 - 3:25 PM 3:25 - 4:15 PM  
Monday       DT (AD2VA1)   MAD (AD2V11)   BDT (AD2513)  
Tuesday                                                 
Wednesday                                               
Thursday                                                
Friday                                                  
Saturday                                            

In [ ]:
!pip install stable_baselines3

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [ ]:
import pandas as pd
import numpy as np
from pymongo import MongoClient

# Connect to MongoDB
client = MongoClient("mongodb+srv://Liyas:1122@cluster0.f8bxeps.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
db = client['ADS']
collection = db['Syllabus']

# Fetch the document
document = collection.find_one()

# Extract data
sem = document['sem']
theory = document['theory']
practicals = document['practicals']
print(theory, practicals)

['AD2511', 'AD2512', 'AD2513', 'AD2514', 'AD2515', 'elective', 'VAC'] ['AD2581', 'AD2591']


In [ ]:
pip install stable_baselines3 pymongo

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
import gym
from gym import Env
from gym.spaces import Discrete, Box, Dict, Tuple, MultiBinary, MultiDiscrete

import numpy as np
import random

from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

In [ ]:
print()

[[2 1 5 3 6 9 1]
 [4 9 2 1 5 1 4]
 [5 7 6 8 1 8 7]
 [4 2 4 7 6 9 3]
 [3 9 0 2 5 8 6]
 [1 7 9 9 3 3 3]]


In [ ]:
class PriceEnv(Env):
  def __init__(self,theory, practicals):
    self.periods = theory + practicals
    self.theory_count = len(theory)
    self.lab_count = 0
    self.action_space = Discrete(len(self.periods))
    self.observation_space = [['']*7 for _ in range(6)]
    self.state = ''
    self.i=0
    self.j=0
    self.told = []

  def step(self, action, bp=-1):
    reward = 0
    done = False
    self.state = self.periods[action]
    if self.theory_count < action:
      if self.told and action in self.told:
        reward -=5
        done = True
      elif self.j==2 or self.j==5:
        for k in range(self.j,self.j+3):
          self.observation_space[self.i][k] = self.state
        self.j +=3
        self.lab_count+=1
        reward+=1
      else:
        reward-=1
        done = True

    else:
      for k in range(self.j):
        if self.observation_space[self.i][k]==self.state:
          reward -= 5
          done = True
      if not(done):
        self.observation_space[self.i][self.j] = self.state
        self.j+=1
        reward += 1

    if self.i==7 and self.j==7:
      reward += 5
      done = True

    if len(self.periods)-self.lab_count-self.theory_count<0:
      reward -= 5
      done = True

    if self.j==7:
      self.j=0
      self.i+=1

    obs = np.array([self.i, self.j])
    info = {}

    return obs, reward, done, info

  def render(self):
    pass

  def reset(self):
    self.action_space = Discrete(len(self.periods))
    self.observation_space = [['']*7 for _ in range(6)]
    self.state = ''
    self.lab_count = 0
    self.i=0
    self.j=0
    return np.array([self.i, self.j])

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
class TimetableEnv(Env):
    def __init__(self, theory, practicals):
        self.periods = theory + practicals
        self.theory_count = len(theory)
        self.lab_count = 0
        self.action_space = Discrete(len(self.periods))

        # Define the observation space as a Box with the appropriate shape
        self.observation_space = Box(low=0, high=len(self.periods), shape=(6, 7), dtype=int)

        # Initialize the actual state as a NumPy array
        self.state = np.zeros((6, 7), dtype=int)
        self.i = 0
        self.j = 0
        self.told = []

    def step(self, action, bp=-1):
        reward = 0
        done = False

        if self.theory_count-1 < action:
          if self.told and action in self.told:
            reward -= 2
            done = True
          elif self.j == 1 or self.j == 4:
              for k in range(self.j, self.j + 3):
                  self.state[self.i][k] = action  # Store action index in the state array
              self.j += 3
              self.lab_count += 1
              reward += 1
              self.told.append(action)
          else:
              reward -= 2
              done = True
        else:
            c=1
            for k in range(self.j):
              if self.state[self.i][k]==action:
                if c>=2:
                  reward -= 2
                  done = True
                else:
                  c+=1
            for k in range(self.i):
                if self.state[k][self.j] == action:
                    reward -= 2
                    done = True
            if not done:
                self.state[self.i][self.j] = action  # Store action index in the state array
                if self.j>0 and self.state[self.i][self.j-1] == action:
                    reward -= 2

                else:
                  reward += 1
                self.j += 1



        if self.i == 7 and self.j == 7:
          if len(self.periods) - self.lab_count - self.theory_count == 0:
            reward += 5
          else:
            reward-=5
          done = True

        if len(self.periods) - self.lab_count - self.theory_count < 0:
            reward -= 2
            done = True

        if self.j == 7:
            self.j = 0
            self.i += 1

        obs = self.state
        info = {}

        return obs, reward, done, info

    def render(self):
        print(self.state)  # Print the current state grid for visualization

    def reset(self):
        self.action_space = Discrete(len(self.periods))
        self.state = np.zeros((6, 7), dtype=int)
        self.lab_count = 0
        self.i = 0
        self.j = 0
        return self.state


In [ ]:
from pymongo import MongoClient

# Connect to MongoDB
client = MongoClient("mongodb+srv://Liyas:1122@cluster0.f8bxeps.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
db = client["ADS"]

# Collection where the semester data is stored
collection_name = "Syllabus"


ModuleNotFoundError: No module named 'pymongo'

In [ ]:
# Create the environment instance
env = TimetableEnv(db=db, collection_name=collection_name)

In [ ]:
import random
import numpy as np
from gym import Env
from gym.spaces import Discrete, Box
from pymongo import MongoClient

class TimetableEnv(Env):
    def __init__(self, db, collection_name):
        self.db = db
        self.collection = self.db[collection_name]
        self.sem_data = self.load_random_semester_data()
        self.update_periods()

        # Define the observation space as a Box with the appropriate shape
        self.observation_space = Box(low=0, high=len(self.periods), shape=(6, 7), dtype=int)

        # Initialize the actual state as a NumPy array
        self.state = np.zeros((6, 7), dtype=int)
        self.i = 0
        self.j = 0
        self.told = []

    def load_random_semester_data(self):
        """Load random semester data from MongoDB."""
        sem_list = list(self.collection.find({}))
        return random.choice(sem_list)

    def update_periods(self):
        """Update periods based on the current semester data."""
        theory = self.sem_data["theory"]["main"] + self.sem_data["theory"].get("elective", []) + self.sem_data["theory"].get("VAC", [])
        practicals = self.sem_data["practicals"]["main"] + self.sem_data["practicals"].get("integrated", [])
        self.periods = theory + practicals
        self.theory_count = len(theory)
        self.lab_count = 0
        self.action_space = Discrete(len(self.periods))

    def step(self, action, bp=-1):
        reward = 0
        done = False

        if self.theory_count - 1 < action:
            if self.told and action in self.told:
                reward -= 2
                done = True
            elif self.j == 1 or self.j == 4:
                for k in range(self.j, self.j + 3):
                    self.state[self.i][k] = action  # Store action index in the state array
                self.j += 3
                self.lab_count += 1
                reward += 1
                self.told.append(action)
            else:
                reward -= 2
                done = True
        else:
            c = 1
            for k in range(self.j):
                if self.state[self.i][k] == action:
                    if c >= 2:
                        reward -= 2
                        done = True
                    else:
                        c += 1
            for k in range(self.i):
                if self.state[k][self.j] == action:
                    reward -= 2
                    done = True
            if not done:
                self.state[self.i][self.j] = action  # Store action index in the state array
                if self.j > 0 and self.state[self.i][self.j - 1] == action:
                    reward -= 2
                else:
                    reward += 1
                self.j += 1

        if self.i == 7 and self.j == 7:
            if len(self.periods) - self.lab_count - self.theory_count == 0:
                reward += 5
            else:
                reward -= 5
            done = True

        if len(self.periods) - self.lab_count - self.theory_count < 0:
            reward -= 2
            done = True

        if self.j == 7:
            self.j = 0
            self.i += 1

        obs = self.state
        info = {}

        return obs, reward, done, info

    def render(self):
        print(self.state)  # Print the current state grid for visualization

    def reset(self):
        self.sem_data = self.load_random_semester_data()
        self.update_periods()
        self.state = np.zeros((6, 7), dtype=int)
        self.lab_count = 0
        self.i = 0
        self.j = 0
        return self.state


In [ ]:
env = TimetableEnv(theory, practicals)

In [ ]:
episodes = 5
for episode in range(1, episodes+1):
  obs = env.reset()
  done = False
  score = 0

  while not done:
    env.render()
    action = env.action_space.sample()
    obs, reward, done, info = env.step(action)
    print(env.observation_space,obs,reward,'\n')
    score+=reward
  print('\tEpisode:{} Score:{}\n\n'.format(episode,score))
env.close()

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Box(0, 9, (6, 7), int64) [[6 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 1 

[[6 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Box(0, 9, (6, 7), int64) [[6 7 7 7 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 1 

[[6 7 7 7 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Box(0, 9, (6, 7), int64) [[6 7 7 7 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 1 

[[6 7 7 7 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Box(0, 9, (6, 7), int64) [[6 7 7 7 1 2 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 1 

[[6 7 7 7 1 2 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0

In [ ]:
import os

In [ ]:
log_path = os.path.join('Training','Logs')
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [ ]:
model.learn(total_timesteps=200000)

Logging to Training/Logs/PPO_42
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 29.8     |
|    ep_rew_mean     | 25.6     |
| time/              |          |
|    fps             | 874      |
|    iterations      | 1        |
|    time_elapsed    | 2        |
|    total_timesteps | 2048     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 29.4        |
|    ep_rew_mean          | 25.4        |
| time/                   |             |
|    fps                  | 735         |
|    iterations           | 2           |
|    time_elapsed         | 5           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.018791225 |
|    clip_fraction        | 0.126       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.159      |
|    explained_variance   | 0.961       

In [ ]:
shower_path = os.path.join('Training','Saved Models','TimeTable_Model_PPO')

In [ ]:
import os
import torch

# Assuming your trained model is available as `model`
save_dir = os.path.join('Training', 'Saved_Models')
os.makedirs(save_dir, exist_ok=True)

# Save the policy network weights
torch.save(model.policy.state_dict(), os.path.join(save_dir, "policy_model.pth"))


In [ ]:
import os
import torch
from stable_baselines3 import PPO

# Load the environment (assuming the environment setup code is available)
# ...

# Re-instantiate the PPO model
model = PPO('MlpPolicy', env)

# Load the saved policy network weights
policy_path = os.path.join('Training', 'Saved_Models', 'policy_model.pth')
model.policy.load_state_dict(torch.load(policy_path))

# Now the model is ready for making predictions


<All keys matched successfully>

In [ ]:
del model

In [ ]:
model = PPO.load(shower_path,env)

In [ ]:
evaluate_policy(model, env, n_eval_episodes=10)

In [ ]:
# Predict the answer (action) using the trained model
obs = env.reset()
done = False

while not done:
    action, _states = model.predict(obs, deterministic=False)
    obs, reward, done, info = env.step(action)
    env.render()

print("Final Observation:\n", obs)

[[6 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[6 3 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[6 3 5 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[6 3 5 2 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[6 3 5 2 6 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[6 3 5 2 6 4 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[6 3 5 2 6 4 2]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[6 3 5 2 6 4 2]
 [2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[6 3 5 2 6 4 2]
 [2 4 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[6 3 5 2 6 4 2]
 [2 4 6 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0

In [ ]:
timetable = [['']*7 for _ in range(6)]

for i in range(6):
  for j in range(7):
    timetable[i][j] = env.periods[obs[i][j]]
print(timetable)

[['VAC', 'AD2514', 'elective', 'AD2513', 'VAC', 'AD2515', 'AD2513'], ['AD2513', 'AD2515', 'VAC', 'elective', 'AD2514', 'VAC', 'AD2514'], ['AD2514', 'elective', 'AD2513', 'AD2512', 'AD2513', 'elective', 'VAC'], ['AD2515', 'VAC', 'AD2515', 'VAC', 'AD2512', 'AD2512', 'AD2511'], ['AD2511', 'AD2511', 'AD2511', 'AD2511', 'AD2511', 'AD2511', 'AD2511'], ['AD2511', 'AD2511', 'AD2511', 'AD2511', 'AD2511', 'AD2511', 'AD2511']]
